### ISSUE TITLE
Treated wood is tagged as a normal plank, causing various issues

### ISSUE THREAD

**Issue by Tors-0** [TerraFirmaGreg-Team/Modpack-Modern#473] opened 2024-09-10 20:25 UTC
### Version modpack Used

1.20.1 0.7.12

### Environment

Forge server

### New Worlds

Yes

### Expected Behavior

Issue 1:
Placing creosote treated wood planks into a barrel of creosote oil and sealing it should do nothing.
Issue 2:
Using treated wood planks to craft fluid pipes should yield treated wood fluid pipes, not normal wood fluid pipes.

### Actual Behavior

Issue 1:
Placing treated wood planks into a barrel of creosote oil consumes more creosote oil continuously to keep treating the "normal planks" into creosote treated planks. This causes even a single wood plank to consume an entire barrel of creosote if left alone.
Issue 2:
Using creosote treated planks to craft treated wood fluid pipe gives normal wood fluid pipes instead, due to them sharing the same crafting recipe.

### Steps to Reproduce

Issue 1:
Place any wood planks into a full barrel of creosote oil and seal it, the plank will become treated, then the timer will restart and the planks will continue being treated over and over.
Issue 2:
Use creosote treated planks to craft treated wood fluid pipes, then shift-click the recipe. This yields normal wood fluid pipes.

**Comment by DracosDragon** [comment] 2024-09-11 00:24
I can confirm having the same issue, i'm fairly certain the root cause is that the NBT tag used for making treated planks from any plank doesn't exclude treated planks, by virtue of them counting as a form of plank block.

**Comment by caelansimms** [comment] 2024-10-22 01:27
This is verified on my playthrough too, on 1.20, 0.7.14 

> i'm fairly certain the root cause is that the NBT tag used for making treated planks from any plank doesn't exclude treated planks, by virtue of them counting as a form of plank block.

I had come to say the same thing. This could be solved by substituting the ``planks`` tag with a new tag that includes all planks except for treated planks, and implementing them in the barrel recipe and the wood fluid pipe recipes.

**Comment by Exzept1on** [comment] 2024-10-26 15:10
Fixed by GT update

**Closed by Exzept1on** 2024-10-26 15:10 UTC
Labels: 1. Type: Bug, 2. Status: Unverified
